#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
#xcompmgr &		# xcompmgr for transparency

mpd &			# music player daemon-you might prefer it as a service though
remapd &		# runs `remaps` now and again whenever a USB input device is plugged in
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources 	# Uncomment to use Xresources colors/settings on startup
xrdb -merge ${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.xresources & # merge with wal config
picom & 		# picom for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
